name: Updates from Repos
on:
  repository_dispatch:
    types:
      [
        update-asd-data-shapes,
        update-asd-debugging-exercise,
        update-snake-fsd,
        update-asd-walker,
        update-asd-image-filtering,
        update-asd-sorting-exercise,
        update-asd-pong
      ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Fetch changes and update
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          REPO_NAME="${{ github.event.client_payload.repo }}"
          EVENT_TYPE="${{ github.event.action }}"

          case $EVENT_TYPE in
            update-data-shapes)
              TARGET_DIR="asd-projects/data-shapes"
              README_NAME="data-shapes.md"
              ;;
            update-debugging-exercise)
              TARGET_DIR="asd-projects/debugging-exercise"
              README_NAME="debugging-exercise.md"
              ;;
            update-snake)
              TARGET_DIR="asd-projects/snake"
              README_NAME="snake.md"
              ;;
            update-walker)
              TARGET_DIR="asd-projects/walker"
              README_NAME="walker.md"
              ;;
            update-image-filtering)
              TARGET_DIR="asd-projects/image-filtering"
              README_NAME="image-filtering.md"
              ;;
            update-sorting-exercise)
              TARGET_DIR="asd-projects/sorting-exercise"
              README_NAME="sorting-exercise.md"
              ;;
            update-pong)
              TARGET_DIR="asd-projects/pong"
              README_NAME="pong.md"
              ;;
          esac

          if [ -n "$TARGET_DIR" ]; then
            # Delete the target directory if it exists
            rm -rf "$TARGET_DIR"
            
            # Clone the repository directly into the target directory
            git clone --depth 1 https://x-access-token:${GITHUB_TOKEN}@github.com/OperationSpark/${REPO_NAME}.git "$TARGET_DIR"
            
            # Remove the .git directory to disconnect it from the source repo
            rm -rf "$TARGET_DIR/.git"
            rm -rf "$TARGET_DIR/.github"
          fi

          # Update README if it exists
          if [ -n "$README_NAME" ]; then
            curl -H "Authorization: token ${GITHUB_TOKEN}" \
                 -H "Accept: application/vnd.github.v3.raw" \
                 -o "project-instructions/$README_NAME" \
                 -L "https://api.github.com/repos/OperationSpark/${REPO_NAME}/contents/README.md"
          fi

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from ${{ github.event.client_payload.repo }}"
          git push